name=input("enter your name:")
USN=input("enter the USN:")
course=input("enter the course:")
div=input("enter the div:")
print(f"student details")
print(f"name:",name)
print(f"USN:",USN)
print(f"course:",course)
print(f"div:",div)
